const PROFILE_TYPE_CLIENT = 'client';
const PROFILE_TYPE_CONTRACTOR = 'contractor';

const CONTRACT_STATUS_NEW = 'new';
const CONTRACT_STATUS_IN_PROGRESS = 'in_progress';
const CONTRACT_STATUS_TERMINATED = 'terminated';

module.exports = {
  PROFILE_TYPE_CLIENT,
  PROFILE_TYPE_CONTRACTOR,
  CONTRACT_STATUS_NEW,
  CONTRACT_STATUS_IN_PROGRESS,
  CONTRACT_STATUS_TERMINATED,
};
